<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE HolyQuran [
	<!ATTLIST HolyQuran TranslationID CDATA #REQUIRED>
	<!ATTLIST HolyQuran Writer CDATA #REQUIRED>
	<!ATTLIST HolyQuran Language CDATA #REQUIRED>
	<!ATTLIST HolyQuran LanguageIsoCode CDATA #REQUIRED>
	<!ATTLIST HolyQuran Direction (rtl|ltr) #REQUIRED>
	<!ELEMENT HolyQuran (Chapter+)>
	<!ATTLIST Chapter ChapterID CDATA #REQUIRED>
	<!ATTLIST Chapter ChapterName CDATA #REQUIRED>
	<!ELEMENT Chapter (Verse+)>
	<!ATTLIST Verse VerseID CDATA #REQUIRED>
	<!ELEMENT Verse (#PCDATA)>
]>
<!-- This SQL Query Generated at 11 August 2018 17:42 (UTC) from www.qurandatabase.org -->
<HolyQuran TranslationID="169" Writer="Şaban Piriş" Language="Turkish" LanguageIsoCode="tur" Direction="ltr">
	<Chapter ChapterID="1" ChapterName="Fatiha">
		<Verse VerseID="1"><![CDATA[Bismillahirrahmânirrahîm.]]></Verse>
		<Verse VerseID="2"><![CDATA[(2-4) Hamd, Alemlerin Rabbi, Rahman, Rahim, din gününün hakimi Allah’a mahsustur.]]></Verse>
		<Verse VerseID="3"><![CDATA[(2-4) Hamd, Alemlerin Rabbi, Rahman, Rahim, din gününün hakimi Allah’a mahsustur.]]></Verse>
		<Verse VerseID="4"><![CDATA[(2-4) Hamd, Alemlerin Rabbi, Rahman, Rahim, din gününün hakimi Allah’a mahsustur.]]></Verse>
		<Verse VerseID="5"><![CDATA[Yalnız sana kulluk ederiz ve yalnız senden yardım dileriz.]]></Verse>
		<Verse VerseID="6"><![CDATA[(6-7) Bizi doğru yola, nimet verdiğin kimselerin yoluna ilet. Gazaba uğrayanların ve sapanların değil..]]></Verse>
		<Verse VerseID="7"><![CDATA[(6-7) Bizi doğru yola, nimet verdiğin kimselerin yoluna ilet. Gazaba uğrayanların ve sapanların değil..]]></Verse>
	</Chapter>
	<Chapter ChapterID="2" ChapterName="Bakara">
		<Verse VerseID="1"><![CDATA[Elif, lâm, Mîm.]]></Verse>
		<Verse VerseID="2"><![CDATA[(2-3) Hiç kuşkusuz bu kitap, kendilerini günahlardan korumaya çalışan, görmediği halde inanan, namazı kılan ve kendilerine verdiğimiz rızıktan (Allah yolunda) harcayanlar için yol göstericidir.]]></Verse>
		<Verse VerseID="3"><![CDATA[(2-3) Hiç kuşkusuz bu kitap, kendilerini günahlardan korumaya çalışan, görmediği halde inanan, namazı kılan ve kendilerine verdiğimiz rızıktan (Allah yolunda) harcayanlar için yol göstericidir.]]></Verse>
		<Verse VerseID="4"><![CDATA[Onlar, sana indirilene, senden önce indirilenlere ve ahirete de kesin olarak inanırlar.]]></Verse>
		<Verse VerseID="5"><![CDATA[İşte, Rab’lerinin yolunda olanlar ve kurtuluşa erecek olanlar onlardır.]]></Verse>
		<Verse VerseID="6"><![CDATA[Kafirlere gelince, onları uyarsan da uyarmasan da birdir, inanmazlar.]]></Verse>
		<Verse VerseID="7"><![CDATA[Allah, onların kalplerini ve kulaklarını mühürlemiştir. Gözlerinde de perde vardır ve onlar için büyük bir azap vardır.]]></Verse>
		<Verse VerseID="8"><![CDATA[İnsanlardan bir kısmı da inanmadığı halde: -Allah’a ve ahiret gününe inandık, diyen kimselerdir.]]></Verse>
		<Verse VerseID="9"><![CDATA[Allah’ı ve inananları aldatmaya uğraşırlar, ama kendilerinden başkasını aldatamazlar da farkında olmazlar.]]></Verse>
		<Verse VerseID="10"><![CDATA[Onların kalplerinde hastalık vardır. Allah da onların hastalığını artırmıştır. Onlara, yalan söylemelerinden dolayı acı veren bir azap vardır.]]></Verse>
		<Verse VerseID="11"><![CDATA[Onlara: -Yeryüzünde bozgunculuk yapmayın, dendiği zaman: -Bizler sadece ıslah edicileriz, derler.]]></Verse>
		<Verse VerseID="12"><![CDATA[İyi bilin ki asıl bozguncular kendileridir, fakat farkında değillerdir.]]></Verse>
		<Verse VerseID="13"><![CDATA[Onlara: -Siz de insanların inandığı gibi inanın! denilince: -Beyinsizlerin inandığı gibi mi inanalım? derler. Dikkat edin! Asıl beyinsizler kendileridir, fakat bilmezler.]]></Verse>
		<Verse VerseID="14"><![CDATA[İnananlara rastladıkları zaman: -İnandık, derler. şeytanları ile başbaşa kalınca da: -Biz, sizin yanınızdayız. Onlarla sadece alay ediyoruz, derler.]]></Verse>
		<Verse VerseID="15"><![CDATA[Allah da onlarla alay eder ve onları taşkınlıkları içinde şaşkın bir halde bırakır.]]></Verse>
		<Verse VerseID="16"><![CDATA[Onlar, hidayet yerine sapıklığı satın aldılar da alışverişleri kar getirmedi ve doğru yolu bulanlar olmadılar.]]></Verse>
		<Verse VerseID="17"><![CDATA[Onların hali, çevresini aydınlatmak için ateş yakan kimsenin haline benzer. Ateş çevresindekileri aydınlattığı sırada Allah onun ışığını giderir ve onları karanlıklar içerisinde görmez bir halde bırakır.]]></Verse>
		<Verse VerseID="18"><![CDATA[Onlar sağır, dilsiz kör kalarak bir daha dönmezler.]]></Verse>
		<Verse VerseID="19"><![CDATA[Yahut, onlar gökten boşanan bir yağmura tutulmuş kimselere benzerler. O yağmurda karanlıklar, gök gürültüsü ve şimşek vardır. Onlar da yıldırımlardan ve ölüm korkusundan parmaklarıyla kulaklarını tıkarlar. Şüphesiz Allah kafirleri çepeçevre kuşatmıştır.]]></Verse>
		<Verse VerseID="20"><![CDATA[Şimşek gözlerini kamaştırır gibi olur; şimşek parıldadığında yürürler, ortalık birden kararınca da orada dikilip kalıverirler, eğer Allah isteseydi onları sağır ve kör ederdi. Allah’ın her şeye gücü yeter.]]></Verse>
		<Verse VerseID="21"><![CDATA[Ey insanlar! Sizi ve sizden öncekileri yaratan Rabbinize kulluk ediniz ki, O’na karşı gelmekten korunmuş olabilesiniz.]]></Verse>
		<Verse VerseID="22"><![CDATA[O, sizin için yeryüzünü döşedi ve gökyüzünü bina etti. Gökten su indirip onunla size rızık olsun diye ürünler yetiştirdi. Öyleyse, bile bile Allah’a eş koşmayın.]]></Verse>
		<Verse VerseID="23"><![CDATA[Kulumuza indirdiğimiz (Kur’an) dan bir şüpheniz varsa; haydi, siz de ona benzer bir sûre getirin eğer doğru sözlüler iseniz Allah’tan başka güvendiklerinizi de yardıma çağırın.]]></Verse>
		<Verse VerseID="24"><![CDATA[Eğer bu işi yapamazsanız -ki elbette yapamayacaksınız- o zaman, kafirler için hazırlanan ve yakıtı insanlar ve taşlar olan ateşten kendinizi koruyun.]]></Verse>
		<Verse VerseID="25"><![CDATA[İman edenler ve doğruları yapanlara, içinden ırmaklar akan cennetler olduğunu müjdele!.. Ne zaman oradaki meyvelerden rızıklandırılsalar: -Bu, daha önce de rızıklandığımız şey! diyecekler. O meyveler kendilerine dünyadakilerin bir benzeri olarak verilecektir ve orada onlar için tertemiz eşler de vardır ve onlar orada ebedi kalacaklardır.]]></Verse>
		<Verse VerseID="26"><![CDATA[Allah, bir sivrisineği ve onun üzerinde bir şeyi örnek vermekten çekinmez. İman edenler, onun Rab’lerinden gelen bir gerçek olduğunu bilirler, ama kafirler: -Allah, bu misalle ne demek istiyor? derler. Allah, bu misalle bir çoklarını şaşkınlıkta bırakır, bir çoklarını da doğru yola çıkarır, şaşkın bırakılanlar yalnızca yoldan çıkanlardır.]]></Verse>
		<Verse VerseID="27"><![CDATA[Ki onlar, Allah ile yapılan sözleşmeyi kabul ettikten sonra bozanlar, Allah’ın, birleştirilmesini emrettiği şeyi parçalayanlar ve yeryüzünde bozgunculuk yapanlardır. İşte kaybedecek olanlar onlardır.]]></Verse>
		<Verse VerseID="28"><![CDATA[Nasıl olur da Allah’a karşı nankör olabilirsiniz? Oysa, siz cansız iken, size o can verdi. Sonra sizin yine canınızı alacak; sonra da sizi diriltecek ve sonunda yine yalnızca O’na döndürüleceksiniz.]]></Verse>
		<Verse VerseID="29"><![CDATA[Yeryüzündeki her şeyi sizin için yaratan sonra gökyüzüne yönelip yedi kat gök olarak düzenleyen ve her şeyi bilen O’dur.]]></Verse>
		<Verse VerseID="30"><![CDATA[Rabbin meleklere: -Ben yeryüzünde bir yönetici yaratacağım, demişti. Melekler de: -Yeryüzünde bozgunculuk edecek, kan dökecek birilerini mi yaratacaksın? Oysa biz seni durmadan hamd ile tesbih ve takdis ediyoruz, dediler. -Sizin bilmediğiniz şeyleri ben bilirim, dedi.]]></Verse>
		<Verse VerseID="31"><![CDATA[Allah, Adem’e bütün isimleri öğretti. Sonra onları meleklere göstererek:-Eğer sözünüzde samimi iseniz bunların isimlerini bana söyleyin, dedi.]]></Verse>
		<Verse VerseID="32"><![CDATA[-Sen yücesin! Yalnız sen eksiklikten uzaksın senin bize öğrettiğinden başka bizim hiç bir bilgimiz yoktur. Bilen ve hüküm veren sensin, dediler.]]></Verse>
		<Verse VerseID="33"><![CDATA[Allah: -Ey Adem! Onlara, bunların isimlerini haber ver, dedi. Adem de meleklere onların isimlerini haber verince Allah: -Size göklerin ve yerin gaybını şüphesiz ben bilirim demedim mi? Sizin açıkladıklarınızı da gizlediklerinizi de ben bilirim, dedi.]]></Verse>
		<Verse VerseID="34"><![CDATA[Meleklere: -Adem için secde edin, demiştik de onlar da hemen secde edivermişlerdi. Sadece İblis kaçınmış, büyüklenmiş ve kafirlerden olmuştu.]]></Verse>
		<Verse VerseID="35"><![CDATA[-Ey Adem! Sen ve eşin cennette oturun dilediğiniz yerden bol bol yiyin. Yalnız şu ağaca yaklaşmayın, yoksa zalimlerden olursunuz, dedik.]]></Verse>
		<Verse VerseID="36"><![CDATA[Şeytan oradan ikisinin de ayağını kaydırdı, onları bulundukları yerden çıkardı. Biz de onlara: -Birbirinize düşman olarak inin, yeryüzünde bir müddet için yerleşip geçineceksiniz, dedik.]]></Verse>
		<Verse VerseID="37"><![CDATA[Adem, Rabbinden emirler aldı, onları yerine getirdi. Bunun üzerine, Rabbi de tevbesini kabul etti. Nitekim O, tevbeleri daima kabul eden ve merhametli olandır.]]></Verse>
		<Verse VerseID="38"><![CDATA[-Hepiniz oradan inin, dedik. Tarafımdan size bir yol gösterici gelecektir; benim yol göstericime uyan kimselere hiçbir korku yoktur ve onlar üzülecek de değillerdir.]]></Verse>
		<Verse VerseID="39"><![CDATA[Yol göstericimi tanımayıp, ayetlerimizi yalan sayanlar, cehennem halkıdır. Onlar, orada temelli kalacaklardır.]]></Verse>
		<Verse VerseID="40"><![CDATA[-Ey İsrailoğulları, Size verdiğim nimetlerimi hatırlayın. Bana verdiğiniz sözü tutun ki ben de size verdiğim sözü tutayım. Yalnızca benden korkun!]]></Verse>
		<Verse VerseID="41"><![CDATA[Elinizde bulunan Tevrat’ı tasdik edici olarak indirdiğim Kur’an’a inanın ve onu inkar edenlerin ilki siz olmayın. Ayetlerimi az bir pahaya satmayın; yalnızca benden korkun!]]></Verse>
		<Verse VerseID="42"><![CDATA[Hakka batılı karıştırmayın, bile bile hakkı gizlemeyin.]]></Verse>
		<Verse VerseID="43"><![CDATA[Namazı kılın, zekatı verin, (Allah’ın emrine) boyun eğenlerle boyun eğin.]]></Verse>
		<Verse VerseID="44"><![CDATA[İnsanlara iyiliği emredersiniz de kendinizi unutur musunuz? Kitabı okuyup durduğunuz halde düşünmez misiniz?]]></Verse>
		<Verse VerseID="45"><![CDATA[(45-46) Sabır ve namazla Allah’tan yardım isteyin. Rablerine kavuşacak ve O’na döneceklerini umanlar ve Allah’a gerçek bir saygı gösterenlerden başkasına namaz elbette ağır gelir.]]></Verse>
		<Verse VerseID="46"><![CDATA[(45-46) Sabır ve namazla Allah’tan yardım isteyin. Rablerine kavuşacak ve O’na döneceklerini umanlar ve Allah’a gerçek bir saygı gösterenlerden başkasına namaz elbette ağır gelir.]]></Verse>
		<Verse VerseID="47"><![CDATA[Ey İsrailoğulları! Size verdiğim nimeti ve sizi bir zamanlar toplumlara üstün kıldığımı hatırlayın.]]></Verse>
		<Verse VerseID="48"><![CDATA[Kimsenin kimseden faydalanamayacağı, kimseden bir şefaat kabul edilmeyeceği, kimseden bir fidye alınmayacağı ve yardım da görülmeyeceği bir günden kendinizi koruyun.]]></Verse>
		<Verse VerseID="49"><![CDATA[Size işkence eden, kadınlarınızı sağ bırakıp oğullarınızı öldüren Firavun Hanedanından sizi kurtarmıştık. Bunda Rabbiniz´den büyük bir imtihan vardı.]]></Verse>
		<Verse VerseID="50"><![CDATA[Ve sizin için denizi yardık, sizi kurtarıp; gözünüzün önünde, Firavun Hanedanını suda boğmuştuk.]]></Verse>
		<Verse VerseID="51"><![CDATA[Musa ile kırk gece için sözleşmiştik ama siz zalimlik ederek onun arkasından buzağıya tapınmıştınız.]]></Verse>
		<Verse VerseID="52"><![CDATA[Bundan sonra da yine belki şükredersiniz diye sizi affetmiştik.]]></Verse>
		<Verse VerseID="53"><![CDATA[Doğru yola gelesiniz diye Musa’ya kitabı ve furkanı vermiştik.]]></Verse>
		<Verse VerseID="54"><![CDATA[Musa kavmine: -Ey halkım! Siz buzağıyı ilah edinerek kendinize yazık ettiniz. Hemen yaratıcınıza tevbe edip, nefislerinizin hakkından geliniz. Böyle yapmanız, yaratıcınız katında sizin için daha hayırlıdır, o daima tevbeleri kabul eden ve acıyan olduğu için tevbenizi kabul eder, demişti.]]></Verse>
		<Verse VerseID="55"><![CDATA[-Ey Musa, Allah’ı apaçık görmedikçe sana inanmayacağız, demiştiniz de, gözünüz bakıp dururken sizi yıldırım çarpmıştı.]]></Verse>
		<Verse VerseID="56"><![CDATA[Ölümünüzden sonra belki şükredersiniz diye sizi tekrar diriltmiştik.]]></Verse>
		<Verse VerseID="57"><![CDATA[Bulutlarla sizi gölgelendirdik, kudret helvası ve bıldırcın gönderdik. Size rızık olarak verdiğimiz güzel şeylerden yiyin, dedik. Onlar bize değil ancak kendilerine zulmediyorlardı.]]></Verse>
		<Verse VerseID="58"><![CDATA[Hani: -Şu kasabaya girip, dilediğiniz yerden istediğinizi bol bol yiyin. Kapısından secde ederek girin ve “bağışla” deyin de sizi bağışlayalım. Güzel davrananların mükafatını da artıralım, demiştik.]]></Verse>
		<Verse VerseID="59"><![CDATA[Fakat, zulmedenler kendilerine söylenmiş olan sözü başka bir sözle değiştirdiler. Biz de, zalimlere, günah işleyerek yoldan çıktıkları için gökten kahredici bir azap indirmiştik.]]></Verse>
		<Verse VerseID="60"><![CDATA[Musa halkı için su aradığında : -Değneğinle taşa vur, dedik. Ondan on iki pınar fışkırdı ve her grup su içeceği pınarı öğrenmişti. Allah’ın rızkından yiyin, için; fakat yeryüzünde bozguncular olarak, taşkınlık yapmayın!]]></Verse>
		<Verse VerseID="61"><![CDATA[Sizin de: -Ey Musa, biz bir çeşit yemeğe dayanamayız bizim için Rabbine dua et de, bize yerde biten sebze, salatalık, sarımsak, mercimek ve soğan çıkarsın, dediğiniz zaman, Musa: -Hayırlı olanı, daha aşağı olanlarla değiştirmek mi istiyorsunuz? Şehre inin, orada istediğiniz var, demişti. ve onlara alçaklık ve yoksulluk damgası vuruldu. Allah’ın gazabına uğradılar. Bu, onların Allah’ın ayetlerini tanımamalarından, Peygamberlerini haksız yere öldürmelerinden dolayı idi. Bu, isyan etmelerinden ve sınırı aşmalarından dolayı idi.]]></Verse>
		<Verse VerseID="62"><![CDATA[Şüphesiz İnananlar, Yahudiler, Hıristiyanlar ve Sabiilerden kim Allah’a ve ahiret gününe inanır ve doğru olanı yaparsa; onlara Rab’leri yanında mükafatlar vardır. Onlara bir korku da yoktur, üzülmeyeceklerdir.]]></Verse>
		<Verse VerseID="63"><![CDATA[Sizden sapa sağlam söz almıştık. Dağı da üzerinize kaldırmış: -Allah’a karşı gelmekten sakınabilmeniz için size verdiğimiz kitaba kuvvetle sarılın ve onun içindekileri aklınızda tutun, demiştik.]]></Verse>
		<Verse VerseID="64"><![CDATA[Bundan sonra yine yüz çevirmiştiniz; eğer Allah’ın size bol nimet ve merhameti olmasaydı, elbette hüsrana uğrayanlardan olurdunuz.]]></Verse>
		<Verse VerseID="65"><![CDATA[İçinizden cumartesi gününde yasağı çiğneyenleri de elbette biliyorsunuz. İşte biz onlara: -Hor ve aşağılık maymunlar olun, dedik.]]></Verse>
		<Verse VerseID="66"><![CDATA[Böylece onların akıbetini hem önlerinde bulunanlar için, hem de kendilerinden sonra gelecekler için bir ibret ve Allah’tan korkanlar için de bir öğüt vesilesi yaptık.]]></Verse>
		<Verse VerseID="67"><![CDATA[Hani Musa kavmine: -Allah, size bir inek kesmenizi emrediyor, demişti. Onlar: -Bizimle alay mı ediyorsun? demişlerdi. Musa da: -Ben cahillerden olmaktan Allah’a sığınırım, demişti.]]></Verse>
		<Verse VerseID="68"><![CDATA[-Rabbine bizim için dua et de bize onun nasıl bir şey olduğunu açıklasın, dediler. O: -Allah, onun ne pek yaşlı ne de pek körpe, ikisi ortası bir inek olduğunu söylüyor. Artık size emredilen şeyi yapın, dedi.]]></Verse>
		<Verse VerseID="69"><![CDATA[-Bizim için Rabbine dua et de, onun ne renk olduğunu bize iyice açıklasın, dediler. Musa: -Allah, onun, bakanların içini açan, parlak sarı bir inek olduğunu söylüyor, dedi.]]></Verse>
		<Verse VerseID="70"><![CDATA[Onlar: -Rabbine dua et, bize açıkça bildirsin. Çünkü bizce inekler birbirine benzer. Allah dilerse elbette biz hidayete erenlerden oluruz, dediler.]]></Verse>
		<Verse VerseID="71"><![CDATA[Musa: -Rabbim, onun yeri sürüp ekini sulayarak boyunduruk altında ezilmemiş, kusursuz, alacasız bir inek olduğunu söylüyor, dedi. -Şimdi gerçeği bildirdin, deyip ineği kestiler; az kalsın bunu yapmayacaklardı.]]></Verse>
		<Verse VerseID="72"><![CDATA[Siz bir kimseyi öldürmüş ve suçu birbirinize atmıştınız, oysa Allah gizlemekte olduğunuzu ortaya çıkaracaktı.]]></Verse>
		<Verse VerseID="73"><![CDATA[-Bir parçasıyla ona vurun, dedik. İşte Allah ölüleri de böyle diriltir. Ve aklınızı kullanasınız diye size ayetlerini gösterir.]]></Verse>
		<Verse VerseID="74"><![CDATA[Sonra kalpleriniz yine katılaştı. Taş gibi.. hatta daha da katı oldu. Nitekim öyle taşlar vardır ki, içlerinden ırmaklar kaynar, öyle taşlar var ki Allah korkusundan yukarıdan aşağıya yuvarlanırlar. Allah yaptıklarınızdan gafil değildir.]]></Verse>
		<Verse VerseID="75"><![CDATA[Size inanacaklarını mı umuyorsunuz? Oysa onlardan bir grup vardı ki Allah’ın sözünü işitirlerdi de düşünüp akıl erdirdikten sonra, bile bile onu bozarlardı.]]></Verse>
		<Verse VerseID="76"><![CDATA[İnananlarla karşılaştıkları zaman “inandık” derler, birbirleriyle yalnız kaldıklarında: - Rabbiniz´in yanında size karşı delil getirsinler diye mi, Allah’ın size açıkladığını onlara anlatıp duruyorsunuz? Bunu akıl etmiyor musunuz? derlerdi.]]></Verse>
		<Verse VerseID="77"><![CDATA[Onlar, gizlediklerini de açıkladıklarını da Allah’ın bildiğini bilmiyorlar mı?]]></Verse>
		<Verse VerseID="78"><![CDATA[Onların bir kısmının okuyup yazması yoktur. Kitabı bilmezler, bildikleri sadece bir takım yalan ve kuruntulardır. Onlar yalnızca zanneder dururlar.]]></Verse>
		<Verse VerseID="79"><![CDATA[Kitabı kendi elleriyle yazıp sonra onu az bir paraya satabilmek için: -Bu, Allah katındandır, diyenlerin vay haline! Vay ellerinin yazmış olduğundan dolayı başlarına geleceklere! Kazandıklarından dolayı vay onların haline!]]></Verse>
		<Verse VerseID="80"><![CDATA[-Ateş bize sayılı bir kaç günden başka dokunmayacaktır, derler. Onlara: -Allah katından bir söz mü aldınız? Eğer, öyle ise Allah sözünden dönmez; yoksa Allah hakkında bilmediğiniz bir şey mi söylüyorsunuz? de.]]></Verse>
		<Verse VerseID="81"><![CDATA[Gerçek şu ki, günah işleyip günahı kendisini kuşatmış olan kimseler, cehennemlikler işte onlardır. Onlar orada ebedi kalacaklardır.]]></Verse>
		<Verse VerseID="82"><![CDATA[İman edip doğruları yapanlara gelince işte onlar cennetliklerdir. Onlar da orada ebedidirler.]]></Verse>
		<Verse VerseID="83"><![CDATA[İsrailoğullarından: -Allah’tan başkasına kulluk etmeyin, anaya, babaya, yakın akrabaya, yetimlere, yoksullara iyilik edin, insanlara güzel söz söyleyin, namazı kılın, zekatı verin! diye söz almıştık. Sonra siz pek azınız dışında sözünüzden döndünüz ve hala da dönmeye devam ediyorsunuz.]]></Verse>
		<Verse VerseID="84"><![CDATA[Sizden “boş yere kanınızı akıtmayınız, birbirinizi yurdunuzdan çıkarmayınız” diye söz almıştık; sonra siz de söz vermiştiniz ve hala buna şahitlik ediyorsunuz.]]></Verse>
		<Verse VerseID="85"><![CDATA[Buna rağmen, yine birbirinizi öldüren, aranızdan bir grubu yurtlarından süren, onlara karşı günah ve düşmanlıkta birleşen, -onları çıkarmak haramken- size esir olarak geldiklerinde fidyelerini veren kimselersiniz; yoksa, siz, kitabın bir kısmına inanıyorsunuz da bir kısmını inkar mı ediyorsunuz? Şu halde içinizden böyle yapanın cezası dünya hayatında rezil olmak ve kıyamet gününde azabın en şiddetlisine uğratılmaktan başka nedir? Allah sizin yaptıklarınızın hiç birinden gafil değildir.]]></Verse>
		<Verse VerseID="86"><![CDATA[İşte onlar, ahireti satıp, dünya hayatını satın alan kimselerdir. Onlardan azap hiç hafifletilmeyecektir. Ve onlar, hiç bir yardım da göremeyeceklerdir.]]></Verse>
		<Verse VerseID="87"><![CDATA[Andolsun Musa’ya kitap verdik. O’ndan sonra da birbiri ardınca peygamberler gönderdik. Meryem oğlu İsa’ya da belgeler verdik ve O’nu Ruhul Kudüs’le destekledik size ne zaman bir peygamber, hoşunuza gitmeyen bir şey getirse, büyüklük taslayarak, bir kısmını yalancı sayıp bir kısmını da öldüreceksiniz, öyle mi?!]]></Verse>
		<Verse VerseID="88"><![CDATA[-Kalplerimiz perdelidir! dediler. Hayır, Allah, inkarları yüzünden onları lanetlemiştir. Ancak onların çok az bir kısmı inanır.]]></Verse>
		<Verse VerseID="89"><![CDATA[Allah katından, onlara, yanlarında bulunan (Tevrat)ı tasdik eden bir kitap geldiği zaman; daha önce kafirlere karşı kendilerine yardım gelmesini beklerlerken; onlara, bildikleri şey gelince onu inkar ettiler. Allah’ın laneti kafirlerin üzerinedir.]]></Verse>
		<Verse VerseID="90"><![CDATA[Allah’ın kullarından dilediğine, bol ihsanından indirmesini çekemeyerek, Allah’ın indirdiğini inkar etmekle kendilerini ne kötü bir şey karşılığında sattılar, bu yüzden gazap üstüne gazaba uğradılar. Kafirlere alçaltıcı bir azap vardır.]]></Verse>
		<Verse VerseID="91"><![CDATA[Onlara: -Allah’ın indirdiğine inanın, dendiği zaman: -Biz, bize indirilene inanırız, deyip ondan sonra geleni (Kur’an’ı) inkar ederler; halbuki O, ellerinde bulunan Tevrat’ı tasdik eden hak bir kitaptır, Onlara: -Gerçekten size indirilene inanıyor idiyseniz niçin daha önce Allah’ın peygamberlerini öldürüyordunuz? de!]]></Verse>
		<Verse VerseID="92"><![CDATA[Musa, size apaçık delillerle gelmişti de sonra O’nun ardından buzağıyı ilah edinmiştiniz. İşte siz, böyle zalimlersiniz.]]></Verse>
		<Verse VerseID="93"><![CDATA[Bir vakit de sizden üzerinize dağı kaldırarak kesin söz almıştık: -Size verdiğimize kuvvetle sarılın ve dinleyin, demiştik. -İşittik ve karşı geldik, dediler de küfürleri yüzünden gönüllerine buzağı sevgisi sindirildi. De ki: -Eğer mümin iseniz, imanınız size ne kötü şey emrediyor!]]></Verse>
		<Verse VerseID="94"><![CDATA[De ki: -Eğer gerçekten, Allah katında ahiret yurdu kimsenin değil yalnız sizin ise; sözünüzde doğru iseniz, haydi ölümü temenni ediniz!]]></Verse>
		<Verse VerseID="95"><![CDATA[Ama, hayır, elleriyle işlediklerinden dolayı ölümü hiç bir zaman istemezler. Allah, elbette zalim olanları en iyi bilendir.]]></Verse>
		<Verse VerseID="96"><![CDATA[Sen onları öteki insanların hayata en düşkünlerinden; hatta, Allah’a ortak koşanlardan bile yaşamaya daha düşkün bulursun. İçlerinden bazıları bin yıl yaşamak ister; oysa bu onları azaptan kurtaracak değildir. Zira Allah, onların yaptıklarını görendir.]]></Verse>
		<Verse VerseID="97"><![CDATA[De ki: -Cebrail’e düşman olan bilsin ki O, daha önceki kitapları doğrulayan, mü’minler için yol gösterici ve müjde olan Kur’an’ı Allah’ın izniyle senin kalbine indirmiştir.]]></Verse>
		<Verse VerseID="98"><![CDATA[Kim Allah’a, Meleklerine, elçilerine Cebrail’e ve Mîkâil’e düşman olursa, şüphesiz Allah da o kafirlerin düşmanıdır.]]></Verse>
		<Verse VerseID="99"><![CDATA[Andolsun biz, sana apaçık ayetler indirdik. Onları fasıklardan başkası inkar etmez.]]></Verse>
		<Verse VerseID="100"><![CDATA[Onlar ne zaman bir söz vermişlerse, içlerinden bir grup bu sözü bozup atmadı mı? Zaten onların çoğu iman etmezler.]]></Verse>
		<Verse VerseID="101"><![CDATA[Onlara ne zaman yanlarında olanı tasdik eden bir elçi gelse kendilerine kitap verilenlerden bir grup sanki Allah’ın kitabını bilmiyorlarmış gibi arkalarına atarlar.]]></Verse>
		<Verse VerseID="102"><![CDATA[Onlar şeytanların Süleyman’ın saltanatı hakkında uydurdukları şeylere tabi oldular. Oysa Süleyman kafir değildi. Fakat insanlara sihri öğreten şeytanlar kafir idi. Onlar insanlara büyüyü Babil´deki iki meleğe, Harut ile Marut’a indirileni öğretiyorlardı. O ikisi: -Biz bir imtihan vesilesiyiz, sakın kafir olma! demedikçe, hiç kimseye bir şey öğretmiyorlardı. O ikisinden karı ile kocanın arasını ayıracak şeyler öğreniyorlardı. Onlar kendilerine faydalı olanı değil zararlı olanı öğreniyorlardı. Andolsun onlar o büyüyü satın alanın ahirette bir nasibi olmadığını gayet iyi biliyorlardı. Kendilerini sattıkları şeyin ne kadar kötü olduğunu keşke anlasalardı!]]></Verse>
		<Verse VerseID="103"><![CDATA[Keşke onlar iman edip korunmuş olsalardı, elbette Allah katında verilecek sevap daha hayırlı olurdu. Keşke bilselerdi!]]></Verse>
		<Verse VerseID="104"><![CDATA[-Ey iman edenler! “Râinâ” (bizi gözet) demeyin “unzurnâ” (bize bak) deyin ve sözü dinleyin, kafirler için çok acı bir azap vardır.]]></Verse>
		<Verse VerseID="105"><![CDATA[Kitap ehli olan kafirler de, müşrikler de size Rabbinizden hiçbir hayır indirilmesini istemezler. Allah ise rahmetiyle dilediği kimseyi seçerek ihsanda bulunur. Şüphesiz Allah en büyük lütuf ve ihsan sahibidir.]]></Verse>
		<Verse VerseID="106"><![CDATA[Biz neshettiğimiz veya, unutturduğumuz bir ayetin yerine ya ondan daha hayırlısını veya onun benzerini getiririz. Allah’ın her şeye gücünün yettiğini bilmez misin?]]></Verse>
		<Verse VerseID="107"><![CDATA[Göklerin ve yerin hükümranlığının Allah’a ait olduğunu ve sizin Allah’tan başka bir koruyucunuz ve bir yardımcınızın olmadığını bilmez misin?]]></Verse>
		<Verse VerseID="108"><![CDATA[Yoksa siz de daha önce Musa’nın sorguya çekildiği gibi Peygamberinizi sorguya çekmek mi istiyorsunuz? Kim imanı, küfür ile değiştirirse doğru yoldan sapmış olur.]]></Verse>
		<Verse VerseID="109"><![CDATA[Kitap ehlinden olanların bir çoğu, hak kendilerine apaçık belli olduktan sonra, içlerindeki kıskançlık yüzünden, sizi inanmanızdan sonra tekrar küfre döndürmeyi arzu ederler. Öyleyse onlara Allah’ın emri gelinceye kadar ilişmeyiniz, kendi hallerine bırakınız şüphesiz Allah’ın gücü her şeye yeter.]]></Verse>
		<Verse VerseID="110"><![CDATA[-Namazı kılın, zekatı verin, kendiniz için önden ne hayır yollarsanız Allah katında onu bulursunuz. Şüphesiz Allah yaptıklarınızı en iyi görendir!]]></Verse>
		<Verse VerseID="111"><![CDATA[-Yahudi ve Hıristiyan olanlardan başkası cennete giremeyecek! dediler; bu onların kuruntusudur. Onlara de ki: -Eğer doğru söylüyorsanız, delilinizi getirin.]]></Verse>
		<Verse VerseID="112"><![CDATA[-Hayır, işini güzel yaparak kendini tamamen Allah’a teslim eden kimse cennete gidecektir. Rabbi katında ona mükafat vardır. Onlara hiçbir korku yoktur. Üzülecek de değillerdir.]]></Verse>
		<Verse VerseID="113"><![CDATA[Hepsi de (kendilerine indirilen) kitabı okuyup durdukları halde, Yahudiler, Hıristiyanların (doğru) bir şey üzerinde olmadıklarını söylerken, Hıristiyanlar da Yahudilerin (doğru) bir yol üzerinde olmadıklarını söylemektedirler. Bilmeyenler de aynen onların sözlerini söylüyorlar. Allah ise kıyamet günü ihtilafa düştükleri konu hakkında, aralarında elbette hükmünü verecektir.]]></Verse>
		<Verse VerseID="114"><![CDATA[Allah’ın mescitlerinde O’nun isminin anılmasını engelleyenlerden ve onları yıkmaya çalışanlardan daha zalim kim vardır? Onların, oralara girmemeleri, girseler bile korka korka girmeleri gerekir. Onlar için dünyada rezillik, ahirette de büyük bir azap vardır.]]></Verse>
		<Verse VerseID="115"><![CDATA[Doğu da Allah’ındır batı da, ne tarafa yönelirseniz yönelin Allah’ın yönü orasıdır. Şüphesiz Allah her şeyi kuşatandır, bilendir.]]></Verse>
		<Verse VerseID="116"><![CDATA[-Allah çocuk edindi, diyorlar. Hâşâ! O bundan münezzehtir. Bilakis, göklerde ve yerde olanların hepsi O’nundur. Hepsi O’na boyun eğmiştir.]]></Verse>
		<Verse VerseID="117"><![CDATA[O, göklerin ve yerin yaratıcısıdır. Bir şeyin olmasını istediği zaman ona sadece “ol” der, o da hemen oluverir.]]></Verse>
		<Verse VerseID="118"><![CDATA[Bilmeyenler: -Ne olur Allah bizimle konuşsa veya bize bir ayet gelse?! demektedirler. Onlardan öncekiler de tıpkı onların söyledikleri gibi söylemişlerdi; kalpleri (nasıl da) birbirine benzemiş. Oysa biz, iyice bilmek isteyen bir toplum için ayetlerimizi apaçık göstermişizdir.]]></Verse>
		<Verse VerseID="119"><![CDATA[Biz seni hem müjdeci, hem de korkutucu olarak hak ile gönderdik. Cehennem halkından sen sorumlu değilsin.]]></Verse>
		<Verse VerseID="120"><![CDATA[Yahudiler de Hıristiyanlar da, sen onların yoluna uymadıkça, asla senden hoşnut olmazlar. -Asıl doğru yol, Allah’ın gösterdiği yoldur! de. Sana gelen ilimden, sonra eğer onların arzularına uyacak olursan, Allah’tan seni koruyacak bir veli de bir yardımcı da yoktur.]]></Verse>
		<Verse VerseID="121"><![CDATA[Kendilerine verdiğimiz kitabı hakkıyla okuyanlar, işte bunlar O’na iman eden kimselerdir. Onu tanımayanlar ise işte asıl hüsrana uğrayacaklar da onlardır.]]></Verse>
		<Verse VerseID="122"><![CDATA[-Ey İsrailoğulları, Size verdiğim nimeti ve sizi diğer toplumlara üstün kıldığımı hatırlayın.]]></Verse>
		<Verse VerseID="123"><![CDATA[Hiç kimsenin hiç kimse adına bir şey ödemeyeceği, hiç kimseden fidye kabul edilmeyeceği, hiç kimseye şefaatin fayda vermeyeceği ve kendilerine yardım da edilmeyeceği bir günden kendinizi koruyun!]]></Verse>
		<Verse VerseID="124"><![CDATA[(Hatırlayın o zamanı ki) Rabbi İbrahim’i bir takım hükümlerle imtihan etmiş, o da onları tamamen yerine getirince: -Seni insanlara önder yapacağım, buyurmuş, İbrahim de: -Soyumdan gelenlerden de önderler yap, demişti. Allah ise: -Ama zalimler için söz vermiyorum, diye cevap vermişti.]]></Verse>
		<Verse VerseID="125"><![CDATA[Kâbe’yi insanlar için toplanma yeri ve emniyet mahalli kılmış ve: -İbrahim’in makamını namazgah edinin, İbrahim ve İsmail’e de: -Beyt’imi tavaf edenler, ibadete kapananlar, rüku ve secde edenler için temizleyin, diye kuvvetli bir emir vermiştik.]]></Verse>
		<Verse VerseID="126"><![CDATA[Hani İbrahim: -Rabbim! Bu şehri güvenli bir şehir yap, halkından Allah’a ve ahiret gününe inananları çeşitli ürünlerle rızıklandır, demişti. Allah da: -İnkarcı olanı bile az bir süre geçindirir, sonra onu cehennem azabına atarım ne kötü bir akibet! diye buyurmuştu.]]></Verse>
		<Verse VerseID="127"><![CDATA[İbrahim, İsmail’le birlikte Kabe’nin temellerini yükseltiyor (ve şöyle dua ediyorlardı): -Rabbimiz hizmetimizi kabul buyur, şüphesiz sen işitensin, bilensin.]]></Verse>
		<Verse VerseID="128"><![CDATA[Rabbimiz, bizi sana teslim olan iki kul ve soyumuzdan da sana teslim olan bir ümmet çıkar. Bize ibadet yollarımızı göster ve tevbelerimizi kabul et, zira tevbeleri kabul edip, bağışlayan ancak sensin!]]></Verse>
		<Verse VerseID="129"><![CDATA[Rabbimiz onlara içlerinden senin ayetlerini onlara okuyan, kitap ve hikmeti öğreten ve onları (şirkten) arındıran bir resul gönder. Şüphesiz aziz ve hakim olan ancak sensin.]]></Verse>